#!/bin/sh

# SXHKD
sxhkd &

# Polybar
$HOME/ground-config/bin/launchpolybar.sh &

# Language
killall -q gxkb; \
~gxkb &

# Startup
#yandex-disk start &
#    kitty &
    

#bspc monitor -d Desktop Web Terminal Editors
MONITORS=$(xrandr | grep " connected" | wc -l)
echo "Number of monitors is ${MONITORS}"

if [ "${MONITORS}" = "1" ]; then
    for monitor in $(bspc query -M); do
        bspc monitor $monitor -d I II III IV V VI VII VIII IX
    done
else
    for monitor in $(bspc query -M); do
        bspc monitor $monitor -d I II III IV V 
    done
fi

bspc config top_padding           27
bspc config border_width          2
bspc config window_gap            3

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Mouse tweaks
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#RULES#
#FM##
#bspc rule -a Nautilus desktop=^1
#bspc rule -a Alacritty:ranger state=floating follow=on sticky=on
#WEB##

##Firefox Tweaks##
bspc rule -a Firefox:Toolkit sticky=on state=floating
bspc rule -a 'Firefox Beta':Navigator desktop='^2' state=tiled focused=off
bspc rule -a Firefox:SessionManager desktop='^2' state=floating layer=above
bspc rule -a Toplevel:Firefox state=floating
bspc rule -a Firefox:Dialog state=floating
#bspc rule -a Chromium desktop=^2
#bspc rule -a TelegramDesktop desktop=^1 follow=on
#bspc rule -a discord desktop=^1

##TERMINALS##
#bspc rule -a Alacritty desktop=^3 follow=on
#bspc rule -a xterm desktop=^3 follow=on

##EDITORS##
#bspc rule -a Emacs desktop=^4 follow=on state=tiled
#bspc rule -a vim desktop=^4 follow=on
#bpsc rule -a nvim desktop=^4 follow=on
#bspc rule -a Code desktop=^4 follow=on

##OTHER THINGS
#bspc rule -a Pavucontrol state=floating

#FOR ALL WINDOWS
bspc rule -a * follow=on layer=above state=floating center=off
bspc rule -a Dunst follow=off layer=above state=floating
bspc rule -a xfce4-notes floating=on
bspc rule -a Xfce4-appfinder follow=on state=fullscreen
bspc rule -a remotevstplugin64.exe follow=on layer=above state=floating center=off
bspc rule -a Gnome-calculator follow=on layer=above state=floating center=on